# This Dockerfile assumes that ./scripts/docker_data_setup.sh has run already and the data are under notebooks/

FROM python:3.10.16-slim

WORKDIR /home/ubuntu/

SHELL ["/bin/bash", "-c"]

COPY . ./PandasBench

COPY ./requirements.txt .

RUN apt-get update -q \
    && apt-get install -qy time openjdk-17-jdk-headless \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r ./requirements.txt